virtualRtsp:
  sourceUrl: "rtsp://192.168.0.103:8554/c920"

  service:
    loadBalancerIP: "192.168.0.251"

recorder:
  persistence:
    storageClass: lvms-vg1-immediate
    size: 30Gi

recordingsHttp:
  service:
    loadBalancerIP: "192.168.0.252"
