{{- if .Values.recordingsHttp.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: camera-recordings-http

spec:
  type: {{ .Values.recordingsHttp.service.type }}

  {{- with .Values.recordingsHttp.service.loadBalancerIP }}
  loadBalancerIP: {{ . | quote }}
  {{- end }}

  selector:
    app: camera-recordings-http

  ports:
    - name: http
      port: {{ .Values.recordingsHttp.service.port }}
      targetPort: http
      protocol: TCP
{{- end }}
